language: objective-c
os: osx
osx_image: xcode9.3

cache:
  bundler: true
  cocoapods: true
  directories:
    - node_modules

branches:
  only:
    - master

env:
  global:
    - NODE_VERSION=stable
    - CODE_SIGNING_REQUIRED=NO

install:
  - brew tap wix/brew
  - brew install applesimutils
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g react-native-cli
  - npm install -g detox-cli
  - npm install
  - npm run unzip
  - detox clean-framework-cache && detox build-framework-cache

script:
  - npm run test

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - artifacts/**/*.png
    - artifacts/**/*.log
  skip_cleanup: true
  on:
    tags: false

notifications:
  webhooks: https://xc-e2e-webhook.now.sh/
